'use client'
import {useState} from 'react'
type Lot={id:string;name:string}
const modules=[['attendance','簽到表'],['dengue','登革熱照片／報表'],['violation','違規停車照片'],['disaster','防災照片'],['shift','結班報表'],['taxi','計程車折扣']] as const
export default function DataMaintenanceClient({parkingLots}:{parkingLots:Lot[]}){
 const [module,setModule]=useState('attendance');const[lot,setLot]=useState('');const[from,setFrom]=useState('');const[to,setTo]=useState('');const[rows,setRows]=useState<any[]>([]);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const lotMap=new Map(parkingLots.map(x=>[x.id,x.name]));
 async function search(){setBusy(true);setMsg('');try{const p=new URLSearchParams({module});if(lot)p.set('lot',lot);if(from)p.set('from',from);if(to)p.set('to',to);const r=await fetch(`/api/admin/data-maintenance?${p}`,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'讀取失敗');setRows(j.rows||[])}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function del(row:any){if(!confirm('確定永久刪除這筆資料？\n\n若有 Storage 檔案，會連實體檔案一起刪除，無法復原。'))return;const r=await fetch('/api/admin/data-maintenance',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({module,id:row.id})});const j=await r.json();if(!r.ok){alert(j.error||'刪除失敗');return}setRows(x=>x.filter(y=>y.id!==row.id));setMsg('刪除完成，相關實體檔案已同步清除。')}
 function title(r:any){return r.file_name||r.vehicle_plate||r.operator_name||r.work_type||r.id}
 function date(r:any){return r.attendance_month||r.work_date||r.photo_date||r.closing_date||r.discount_date||r.uploaded_at||r.created_at||'-'}
 return <div style={{paddingBottom:40}}><h1>資料維護</h1><p className="muted">僅主管可使用。優先清理會佔 Storage 容量的附件；正式電子合約與簽名留存不列入刪除範圍。</p><div className="card" style={{marginTop:18}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(180px,1fr))',gap:12}}><div className="field"><label>資料類型</label><select value={module} onChange={e=>setModule(e.target.value)}>{modules.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></div><div className="field"><label>停車場</label><select value={lot} onChange={e=>setLot(e.target.value)}><option value="">全部</option>{parkingLots.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></div><div className="field"><label>開始日期</label><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div className="field"><label>結束日期</label><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></div></div><button className="btn" type="button" onClick={search} disabled={busy} style={{marginTop:14}}>{busy?'讀取中…':'查詢資料'}</button>{msg&&<div style={{marginTop:12,fontWeight:700}}>{msg}</div>}</div><div className="card" style={{marginTop:18}}><h2 style={{marginTop:0}}>查詢結果（最多 200 筆）</h2><div style={{overflowX:'auto'}}><table className="table" style={{minWidth:760}}><thead><tr><th>停車場</th><th>日期</th><th>資料</th><th>大小</th><th>操作</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{lotMap.get(r.parking_lot_id)||'-'}</td><td>{String(date(r)).slice(0,19)}</td><td>{title(r)}</td><td>{r.file_size?`${(Number(r.file_size)/1024/1024).toFixed(2)} MB`:'-'}</td><td><button type="button" onClick={()=>del(r)} style={{background:'#b91c1c',color:'#fff',border:0,borderRadius:8,padding:'8px 12px',fontWeight:700,cursor:'pointer'}}>永久刪除</button></td></tr>)}{rows.length===0&&<tr><td colSpan={5} style={{textAlign:'center',padding:24}}>請先查詢</td></tr>}</tbody></table></div></div></div>
}
